CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'bakilic'@'%' IDENTIFIED BY '123';
GRANT ALL PRIVILEGES ON wordpress.* TO 'bakilic'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root123';
